### ISSUE TITLE
Contao 4.4 buttons in simple modal window are not active

### ISSUE THREAD

**Issue by qzminski** [terminal42/contao-dcawizard#19]
https://github.com/isotope/core/issues/1819

**Comment by qzminski** [comment]
@aschempp @Toflar the only reasonable solution I can think of is 6591953.

**Comment by Toflar** [comment]
Actually, this is caused by https://github.com/contao/core-bundle/blob/master/src/Resources/contao/templates/backend/be_main.html5#L95-L103 and I don't know if we should consider this a Contao bug. I mean, why should Contao decide to disable **every** button in **every** modal if there is nothing to pick. I'm sorry but there are many reasons to open something in a popup, why should Contao just disable the buttons. This is nonsense. This should only happen in picker mode. /cc @leofeyer

**Comment by Toflar** [comment]
Does https://github.com/contao/core-bundle/commit/6a7d052a4b08047e4d42cd9f084d27d195aea0b1 fix that?

**Comment by leofeyer** [comment]
It probably does not.

**Comment by aschempp** [comment]
Maybe if we would only match for `act=select`?

**Comment by leofeyer** [comment]
No, we will have to match the `extras` parameter of the picker. If it is not present, we must not mess with the apply button. 😄

**Comment by Toflar** [comment]
Is that true, @aschempp? If so, please include in your PR for the picker :)

**Comment by aschempp** [comment]
That is not true. The picker value will be there in the select-multiple as well. Having or not having a picker does not define if the buttons are available.

**Comment by qzminski** [comment]
Fixed in 0d564e45880934a96d1c3a3865c5320ddb0d3f77.
