### ISSUE TITLE
Contao 4.4 Missing method StringUtil::ampersand

### ISSUE THREAD

**Issue by Songworks** [terminal42/contao-dcawizard#37]
The method `\DcaWizard::getButtonHref` uses `\Contao\StringUtil::ampersand`, which unfortunately does not exist in Contao 4.4.

Instead, Contao 4.4 has the function `ampersand` for the same purpose (same code within the function too).

According to your composer.json, the plugin still supports Contao 4.4?
Is this something you could (or were willing) to fix?
I understand if you won't, 4.4 is end of life after all.

Anyway, I had someone else come across this problem.
I will ask them to update to at least Contao 4.9 in either case.

Cheers!

**Comment by Webstylerin** [comment]
I encountered the same problem after updating a Contao 4.4 site to 4.4.57. I can no longer access the message settings in the notification_center because I get an error message:

`Attempted to call an undefined method named "ampersand" of class "Contao\StringUtil".`

I have changed what needs to be changed directly in the database, but this is not a solution for other users.

However, I will also suggest a Contao update.

**Comment by Toflar** [comment]
Yeah, we already have a hard time maintaining all our extensions for free anyway so I don't think we'll maintain stuff for outdated versions - that would only make things worse 😄  We should increase the minimum requirements in the next version though.

**Comment by aschempp** [comment]
fixed in 2be082a7f2c7cd58c4656880a9a6729d9a6a7a2f
